MMORPG_board/MMORPG_board/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('board.urls')),
    path('accounts/', include('allauth.urls')),
    path('subaccountsystem/', include('subaccount_system.urls')),
    path('tinymce/', include('tinymce.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MMORPG_board/board/urls.py
from django.views.decorators.cache import cache_page
from django.urls import path

from .views import AnnouncementsList, CreateAnnouncement, ResponsesList, AnnouncementDetail

urlpatterns = [
    path('', cache_page(0)(AnnouncementsList.as_view()), name='board'),
    path('createannouncement/', CreateAnnouncement.as_view(), name='create_announcement'),
    path('<int:pk>', AnnouncementDetail.as_view(), name='announcement'),
    path('responses/', cache_page(0)(ResponsesList.as_view()), name='responses'),
]

MMORPG_board/board/models.py
from django.db import models
from tinymce import models as tinymce_models


class Announcement(models.Model):
    CATEGORIES = [
        ('Танки', 'Танки'),
        ('Хилы', 'Хилы'),
        ('ДД', 'ДД'),
        ('Торговцы', 'Торговцы'),
        ('Гилдмастеры', 'Гилдмастеры'),
        ('Квестгиверы', 'Квестгиверы'),
        ('Кузнецы', 'Кузнецы'),
        ('Кожевники', 'Кожевники'),
        ('Зельевары', 'Зельевары'),
        ('Мастера заклинаний', 'Мастера заклинаний'),
    ]
    author = models.ForeignKey('subaccount_system.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=120)
    text = tinymce_models.HTMLField()
    date_created = models.DateTimeField(auto_now_add=True)
    date_edit = models.DateTimeField(auto_now_add=True)
    category = models.CharField(max_length=30, choices=CATEGORIES)
    active = models.BooleanField(default=True)


class UserResponse(models.Model):
    responder = models.ForeignKey('subaccount_system.User', on_delete=models.CASCADE)
    announcement = models.ForeignKey(Announcement, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)
    text = tinymce_models.HTMLField()
    accepted = models.BooleanField(default=False)
    rejected = models.BooleanField(default=False)

MMORPG_board/templates/default.html
<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Доска объявлений</title>

        {% load static %}

        <!-- Core theme CSS (includes Bootstrap)-->
        <script src="{% static 'tinymce/tinymce.min.js' %}"></script>
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container px-lg-5">
                <a class="navbar-brand" href="{% url 'board' %}">Доска объявлений</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        {% if user.username %}
                            <li>
                                <span class="nav-link">Пользователь: {{ user.username }}</span>
                            </li>
                        {% endif %}
                        {% if perms.board.add_announcement %}
                            <li class="nav-item active">
                               <a class="nav-link" href="{% url 'create_announcement' %}">Разместить объявление</a>
                            </li>
                        {% endif %}
                        {% if perms.board.view_userresponse %}
                            <li class="nav-item active">
                               <a class="nav-link" href="{% url 'responses' %}">Отклики</a>
                            </li>
                        {% endif %}
                        <li>
                           <a class="nav-link" href="{% url 'account_login' %}">Log in</a>
                        </li>
                        <li>
                           <a class="nav-link" href="{% url 'account_logout' %}">Log out</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Content-->
        <section class="pt-4">
            <div class="container px-lg-5">
                {% block content %}
                {{ flatpage.content }}
                {% endblock content %}
            </div>
        </section>
    </body>
</html>